name: docs

on:
  push:
    branches:
      - master

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          # Install poetry package manager
          pip install poetry

          # Install dependencies with poetry
          poetry install

      - name: Build docs and push them to gh-pages branch
        run: |

          # Build docs
          make -C docs clean
          make -C docs html
        
          # Copy built results to the temporary directory
          docsdir=$(mktemp -d)
          rsync -av "docs/_build/html/" "${docsdir}/"

          # Change git username
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"

          # Init empty repo in tmp directory
          pushd "${docsdir}"
          git -C "${docsdir}" init
          git -C "${docsdir}" remote add deploy "https://token:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git"
          git -C "${docsdir}" checkout -b gh-pages

          # Prevents contents of the branch from being build as Jekyll sources
          touch .nojekyll

          # Add README disclaimer
          echo "# GitHub Pages for `ilexconf`" >> README.md
          echo "The contents of this branch are built using GitHub Actions workflow and Sphinx." >> README.md
          echo "See built docs on [ilexconf.com](https://ilexconf.com)" >> README.md

          # Push everything to GitHub's remote branch
          git -C "${docsdir}" add .
          git -C "${docsdir}" commit -m "ğŸ“ Rebuilt docs for commit ${GITHUB_SHA:0:6}"
          git -C "${docsdir}" push deploy gh-pages --force
