name: release

on: [push, pull_request]

jobs:

  setup:
    runs-on: ubuntu-latest
    #strategy:
      #matrix:
        #python-version: [2.7, 3.5, 3.6, 3.7, 3.8]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
          # python-version: ${{ matrix.python-version }}
      - uses: ./.github/actions/setup

  test:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - uses: ./.github/actions/setup
      - name: Tests
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: |
          # Run tests
          poetry run pytest --cov --cov-report=xml

          # Send results to codecov
          bash <(curl -s https://codecov.io/bash)
        
  publish:
    runs-on: ubuntu-latest
    needs: test
    if: contains(github.ref, 'master')
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - uses: ./.github/actions/setup
      - name: Build and push to PyPI
        env:
          PYPI_USERNAME: "${{ secrets.PYPI_USERNAME }}"
          PYPI_PASSWORD: "${{ secrets.PYPI_PASSWORD }}"
        run: |
          # Change version
          sed -i "s/\(version = \"[[:digit:]]\.[[:digit:]]\).*\"/\1.$GITHUB_RUN_NUMBER\"/" ./pyproject.toml

          # Publish
          poetry publish --build --username "$PYPI_USERNAME" --password "$PYPI_PASSWORD"
